spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student-micro-service
    username: postgres
    password: erkin
    driver-class-name: org.postgresql.Driver  # Добавлено для явного указания драйвера
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8080

address:
  server:
    url: http://localhost:8082

resilience4j:
  circuitbreaker:
    instances:
      addressService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30000
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 5
        allow-health-indicator-to-fail: true
        register-health-indicator: true

management:
  health:
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
